### ISSUE TITLE
npm run build gives errors

### ISSUE THREAD

**Issue by jonaskello** [piotrwitek/react-ts-jspm-starter-kit#17]
Maybe just on my computer, but I get this on a freshly cloned copy of this repo:

```
$ npm run build

> react-redux-typescript-starter-kit@0.10.0 build C:\temp\react-redux-typescript-starter-kit
> npm run build:app && npm run build:vendor


> react-redux-typescript-starter-kit@0.10.0 build:app C:\temp\react-redux-typescript-starter-kit
> npm run _jspm-build-app -- --skip-source-maps --minify


> react-redux-typescript-starter-kit@0.10.0 _jspm-build-app C:\temp\react-redux-typescript-starter-kit
> jspm build src/app - bundle-config.vendor.js dist/app.js "--skip-source-maps" "--minify"

module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Temp\react-redux-typescript-starter-kit\node_modules\jspm\jspm.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by jonaskello** [comment]
Forget about it, forgot to run npm install after I cloned the repo! I still have trouble getting the build to run in my project that is based on this starter but that is probably related to some changes I made outside of the starter-kit. Sorry for the non-issue!
