### ISSUE TITLE
Installing behind a proxy

### ISSUE THREAD

**Issue by jakub-astrahit** [piotrwitek/react-ts-jspm-starter-kit#62]
Hi, here's an issue I'm having when I try to install this repo behind a proxy. When I run this script: `npm run init`, I get these errors:
```
> react-redux-typescript-jspm-starter@0.12.0 init 
> jspm install && npm run dev:bundle

     Creating registry cache...

warn Error on locate for github:systemjs/plugin-css, retrying (1).
     Error: connect ECONNREFUSED 192.30.253.113:443
         at Object._errnoException (util.js:1022:11)
         at _exceptionWithHostPort (util.js:1044:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

warn Error on locate for github:frankwallis/plugin-typescript, retrying (1).
     Error: connect ECONNREFUSED 192.30.253.113:443
         at Object._errnoException (util.js:1022:11)
         at _exceptionWithHostPort (util.js:1044:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

warn Error on locate for github:alexisvincent/systemjs-hot-reloader, retrying (1).
     Error: connect ECONNREFUSED 192.30.253.112:443
         at Object._errnoException (util.js:1022:11)
         at _exceptionWithHostPort (util.js:1044:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

err  Error on lookup for npm:tslib
Error: connect ECONNREFUSED 151.101.112.162:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

err  Error looking up npm:tslib.

warn Installation changes not saved.
```

How can I set up a proxy for installing this please? Is it even possible?

I tried running this but it didn't help: `setx HTTPS_PROXY <proxy>`

**Comment by piotrwitek** [comment]
No idea, I would suggest to look through issues in the jspm repo or StackOverflow

**Comment by jakub-astrahit** [comment]
@piotrwitek Still no luck even after setting my environment variables, git proxy etc. Is there a way I can skip this step (`npm run init`) and avoid jspm with this repo?

For now, I ended up copying the jspm_packages folder manually from outside proxy (different computer), and then instead of running `npm run init`, I just ran this: `npm run dev:bundle`

**Comment by js2me** [comment]
Hello, try :
```
npm config set HTTP_PROXY <proxy>
npm config set HTTPS_PROXY <proxy>
```

**Comment by jakub-astrahit** [comment]
@js2me Didn't work.
